apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rocket-app
  labels:
    name: rocket-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: rocket-app
    spec:
      containers:
      - name: rocket
        image: rocket:v0.0.11
        env:
        - name: "ROCKET_ENV"
          value: "staging"
